name: Deploy Backend to EC2

on:
  push:
    branches:
      - main
    paths:
      - "backend/**"
      - ".github/workflows/deploy.yml"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy Backend to EC2
        uses: appleboy/ssh-action@v1.2.2
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}

          script: |
            set -e

            cd /var/www/split-backend/Split-Expense

            git fetch origin main
            git reset --hard origin/main

            cd backend

            npm ci --omit=dev

            pm2 restart split-backend --update-env
            pm2 save

            echo "Backend deployment completed successfully"